import { z } from "zod"

export const profileSchema = z.object({
  fullName: z.string().min(2, "Full name is required."),
  username: z.string().min(3, "Username must be at least 3 characters."),
  email: z.string().email("Enter a valid email address."),
  phone: z.string().min(7, "Phone number is required."),
  location: z.string().min(2, "Location is required."),
  timezone: z.string().min(2, "Timezone is required."),
  languages: z.string().min(2, "Add at least one language."),
  title: z.string().optional(),
  bio: z.string().optional(),
  experienceLevel: z.string().optional(),
  hourlyRate: z.coerce.number().min(0, "Hourly rate must be at least $0.").optional(),
  availability: z.string().optional(),
  portfolioWebsite: z.union([z.literal(""), z.string().trim().url("Enter a valid URL.")]),
  github: z.union([z.literal(""), z.string().trim().url("Enter a valid URL.")]),
  linkedin: z.union([z.literal(""), z.string().trim().url("Enter a valid URL.")]),
  preferredJobType: z.string().optional(),
  budgetRange: z.string().optional(),
  weeklyAvailability: z.string().optional(),
  remoteOnly: z.boolean(),
  openToContract: z.boolean(),
  twoFactor: z.boolean(),
})

export type ProfileFormValues = z.infer<typeof profileSchema>

export const defaultProfileValues: ProfileFormValues = {
  fullName: "",
  username: "",
  email: "",
  phone: "",
  location: "",
  timezone: "",
  languages: "",
  title: "",
  bio: "",
  experienceLevel: "",
  hourlyRate: 0,
  availability: "",
  portfolioWebsite: "",
  github: "",
  linkedin: "",
  preferredJobType: "",
  budgetRange: "",
  weeklyAvailability: "",
  remoteOnly: false,
  openToContract: false,
  twoFactor: false,
}
